- name: Demo the Ansible Collection
  hosts: all

  tasks:
   - name: Gather some real facts.
     newswangerd.collection_demo.real_facts:
       name: Phil Griffiths
     register: testout
   - debug:
       msg: "{{ testout }}"
